application: invpanoramio
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /stylesheets
  static_dir: stylesheets

#- url: /datastore_admin
#  script: /home/mmoghimi/programs/google_appengine/google/appengine/ext/datastore_admin/main.py

- url: /datastore_admin_secret
  script: datastore_admin.py

- url: /.*
  script: invpanoramio.app

#- url: /test_gps.html
#  static_files: test_gps.html
#  upload: test_gps.html


libraries:
- name: jinja2
  version: latest
 
builtins:
- datastore_admin: on
